-- Data migration: Batu Ozcelik's session logs, transcribed from the client's
-- "Batu" sheet (Anugya / Bharat / Ylenia / Magdaleina / Jesse / Sajjad).
--
-- Every row is an Academic (course type) / Academics (program type) session
-- with Rana Walid as the coordinating performance coach. `topic` is the short
-- subject/topic label from the sheet (derived from the summary where the sheet
-- only gave prose), `fathom_summary` is the sheet's summary/transcript text and
-- `video_link` its Fathom recording. Session numbering, the sheet's second
-- numeric column, and the row for a different student (Erez Ariel) are not
-- carried over. `student_package_id` is filled in by
-- handle_session_log_package_lock() on insert.

insert into public.session_logs (
  student_id, student_first_name, student_last_name, session_date,
  session_duration_hrs, program_type_id, course_type_id, subject_id,
  curriculum_id, topic, video_link, fathom_summary, teacher_id,
  coordinator_teacher_id, no_show_type, flag_for_coach
)
select
  st.id, st.first_name, st.last_name, v.session_date,
  v.duration_hrs, pt.id, ct.id, s.id,
  c.id, v.topic, v.video_link, v.summary, t.id,
  pc.id, null, false
from (values
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-02-03'::date, 1, 'MYP mock preparation: command terms and Criterion A & B technique', 'In this one-hour session, we focused on preparing for the upcoming MYP Integrated Humanities mock by strengthening exam technique and conceptual understanding. We clarified key command terms, particularly the difference between explain and describe, and practised applying them accurately in exam-style questions. We refined the structure of 6-mark responses using the 1-4-1 format and worked on improving research question justification for Criterion B through a clear three-step framework linked to the Statement of Inquiry. The session helped identify key areas for further practice, especially Criterion A and B questions, and concluded with clear action steps to consolidate learning before the mock exam. Homework waas given to complete one question for Crit. A and Crit. B based on the detailed notes and structure shared by me on group.', 'https://fathom.video/share/H43gAzsrLgKJJQKqABAMGs2vCAJLen2f'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-02-07'::date, 1, 'The tundra ecosystem: fragility and the impacts of climate change', 'In this one-hour session, we explored the tundra ecosystem and examined why it is considered one of the most fragile biomes on Earth. We discussed how extreme cold temperatures, permafrost, low biodiversity, and very slow recovery rates make the tundra highly vulnerable to disturbance. The session then focused on the impacts of climate change, particularly permafrost thaw, soil instability, and shrub expansion, and how these changes accelerate warming and disrupt ecosystems. We also examined the challenges faced by human activities and indigenous communities, including damage to infrastructure and threats to traditional livelihoods. The lesson concluded with a recap linking environmental fragility to long-term ecological and human consequences in the tundra region.', 'https://fathom.video/share/Zku6ffTDqeba9G3LrXyfJBDoHnarP2vu'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-02-08'::date, 1, 'Criterion A & D command terms: mining in the tundra and compare-and-contrast questions', 'In this one-hour session, we focused on strengthening exam technique by reviewing assessment command terms and applying them to environmental case-study questions. We began by revisiting Criteria A, clarifying expectations for command terms such as describe and explain, before moving on to Criteria D, which requires deeper analytical thinking. We practised analysing the environmental consequences of mining in the tundra, considering impacts on permafrost, wildlife, biodiversity, and climate change, and emphasised the need for a structured response with a clear introduction, analysis, and balanced conclusion. We also worked on compare and contrast questions by examining the challenges of sustainable management in deserts and rainforests, focusing on similarities and differences in resource use, biodiversity, and human pressure. The session concluded with feedback on the compare and contrast question he did in class and will finish that as homework now.', 'https://fathom.video/share/W8ZSRYsWDfY9yZAnK2ns3oovrHZAPVYG'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-02-21'::date, 1, 'Criterion C formats: articles, speeches, reports, letters, diary entries and monologues', 'In this one-hour session,, we focused on understanding the different formatting requirements for Criterion C tasks, including articles, speeches, reports, letters, diary entries, and monologues, with guidance on structure and key elements for each. The lesson concluded with Batu being assigned two Criterion C tasks, one on UN peacekeeping and another proposing a solution to protect a biome, along with additional resources and clear expectations for completion.', 'https://fathom.video/share/yD83MS-E_ExuUMjyM4mG2LXGkpJb7ymt'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-03-07'::date, 1, 'UN Peacekeeping article revision and a formal speech on rainforest protection', 'In this one-hour session with Batu, we reviewed his writing assignments and clarified key content related to UN topics. We revised his article on United Nations Peacekeeping Forces, correcting the confusion between the diplomatic role of the United Nations and the operational responsibilities of peacekeeping troops. The article was restructured using the United Nations Peacekeeping Force in Cyprus as a case study to illustrate functions such as monitoring buffer zones, supporting ceasefires, and providing humanitarian assistance. The session also included guidance on drafting a formal speech proposing sustainable solutions for rainforest protection, with emphasis on using credible information and avoiding unreliable statistics. We concluded with Batu continuing the speech draft as homework using a structured speech format for review in the next session.', 'https://fathom.video/share/K1ynbeQEgC93EJRgAeQgLWMtERz4uHcT'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-03-14'::date, 1, 'UN speech feedback and compare-and-contrast: sustainable management in deserts and rainforests', 'This one-hour session focused on improving his writing and analytical skills through feedback on his UN speech proposal, where he was guided to strengthen the introduction, make the argument more solution-oriented, and include clearer, actionable ideas. We also practised a compare-and-contrast approach by analysing the challenges of sustainable management in desert and rainforest ecosystems, focusing on factors such as water availability, biodiversity, and human pressures. The session concluded with a recap of feedback and a homework task to complete the conclusion of the ongoing compare and contrast answer and to attempt one question on evaluation command term.', 'https://fathom.video/share/4h-Nws1GKWnD2psz1N7aNF3TaofikX-4'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-03-28'::date, 2, 'Sustainable management of rainforests and OPVL source analysis', 'In this two-hour session, I began with providing feedback on improving structure, particularly by adding a clear introduction and better contextual explanation of sustainable management in rainforests which was his home task given in the last session. We then shifted focus to developing source analysis skills through OPVL (Origin, Purpose, Value, Limitations), where I guided him on structuring responses effectively using a trade-related source. He attempted one task based on the trade aid and exchange case study of China, based on Criterion. A- ''explain''. The lesson concluded with a recap and clear next steps, including further practice of OPVL analysis and revisiting key content in upcoming sessions', 'https://fathom.video/share/qbQcHJsy6XyyFv1sun6n2Q1s3H23bGbx'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-05'::date, 2, 'OPVL on China-India trade, impacts of World War II, and theories of social groups', 'In this two-hour session, we focused on strengthening IB History skills by combining source analysis, content revision, and conceptual understanding. We began with practicing OPVL analysis using a case study article on China-India trade, where we identified key values and limitations such as its business-focused perspective and potential nationalistic bias. The session then moved to revising the impacts of World War II, including the rise of the USA and USSR as superpowers, the creation of the United Nations, decolonization, and the origins of the Cold War, while also identifying gaps in understanding key causes of the war that will be addressed in future lessons. We concluded by introducing foundational theories on social groups, including Maslow''s Hierarchy of Needs, Durkheim''s types of solidarity, and Marx''s economic systems, helping build a strong conceptual base for interdisciplinary connections.', 'https://fathom.video/share/weWLCaHrriUoP9iCkgyxg6zu3pZH2Mer'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-09'::date, 2, 'Introduction to international trade: comparative advantage, balance of trade, free vs fair trade', 'In this two-hour session, I introduced Batu to the concept of international trade, beginning with a clear definition of trade as the voluntary exchange of goods and services and tracing its origins through early civilizations and major historical routes like the Silk Road and the Spice Route. I explained the significance of these trade networks in shaping global economic connections and the movement of valuable goods. The session then focused on key economic concepts, including the difference between absolute and comparative advantage, and why countries engage in international trade based on factors such as resources, population, and development levels. I also covered the balance of trade and balance of payments, helping Batu understand how countries track their economic interactions globally. In addition, I explored the differences between free trade and fair trade, discussing their advantages and limitations. The session concluded with a recap of all key concepts and the assignment of homework to reinforce understanding and prepare for the next lesson.', 'https://fathom.video/share/1cyyhuaeQj9v86jxCvydNzxMz3Wk5Fmk'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-11'::date, 1, 'Press release feedback: evaluating free trade and protectionism', 'In this one-hour session, I addressed Batu''s incomplete homework and adjusted our schedule to ensure more time for writing practice in future sessions. I provided detailed feedback on his press release draft, highlighting that it did not fully meet the task requirements and lacked proper structure, evaluation, and balance. I guided him on how to approach the task more effectively by clearly analysing both free trade and protectionism, using relevant economic concepts and examples, and presenting a well-supported recommendation from a journalist''s perspective. The session concluded with a recap of expectations for the assignment and clear next steps, including reviewing the shared materials and preparing to improve his response in the next class.', 'https://fathom.video/share/VUFyLTTJbagy-LBCyn7cuSXLWt7hLC5V'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-18'::date, 2, 'Criterion B: formulating research questions, justification and sources', 'In this two-hour session, we worked extensively on formulating effective research questions, emphasizing that they must be specific, begin with ''to what extent,'' and clearly define a topic, time frame, and context. Using the example of the internet, I guided Batu through refining his research question and building a structured justification using a three-part framework, ensuring he connected the statement of inquiry to his chosen topic without directly answering the question. We also explored primary and secondary sources, methods of data collection, and potential research challenges, reinforcing how each component must align with the research focus. To consolidate learning, we practiced a second research question on mining in the tundra biome and its impact on biodiversity, where Batu began drafting his justification with guidance. The session concluded with clear homework to complete the justification and continue practicing research-based responses to strengthen his understanding of Criterion B.', 'https://fathom.video/share/qMWMjoeLTb52sERZizkm75UYupPmroVy'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-19'::date, 2, 'Criterion B justification review and the globalisation speech', 'In this two-hour session, I reviewed Batu''s Criterion B work and confirmed that his research question was well-structured, including a clear time period, location, and connection to the statement of inquiry. I guided him on improving the flow of his justification, particularly avoiding repetition and following a logical structure. We also discussed relevant data, primary and secondary sources, and the issue of bias, especially when using company reports. The session then shifted to his globalization speech, where I helped him refine the definition, improve structure, and strengthen arguments using examples such as the Great Depression and COVID-19. I emphasized the importance of completing a full response before seeking feedback. However, Batu is not taking the subject seriously, shows overconfidence in his content knowledge, and resists following IB structure-particularly the writing component-which is limiting his progress in Integrated Humanities.', 'https://fathom.video/share/V6ZhYwQsoLW95ZYf3M5gjt_zH_xWyKgt'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-25'::date, 2, 'Criterion A & D homework review, M25 past paper and the 8-mark evaluation question', 'In this session, I reviewed Batu''s homework, where he scored 5/8 in Criterion A and 3/8 in Criterion D. I emphasized the importance of using proper references from the source and introduced a past paper (M25) to guide him through different question types. I supported him in improving his answers by adding specific examples and context. A key focus was the 8-mark evaluation question, where I trained him to develop well-reasoned strengths and limitations with clear and balanced appraisal. We also worked on Criterion B, including justifying a research question on the Treaty of Versailles and selecting appropriate primary sources. Towards the end, I assigned an 18-mark speech on quality of life indicators, advising him to improve structure, tone, and include a strong call to action.', 'https://fathom.video/share/WtR4RakdMrf6zSKg91Hy54sEw2F8Mx95'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-04-26'::date, 2, 'Past paper practice: persuasive speech, OPVL on water stress and the 24-mark essay', 'In this session, I guided Batu through completing multiple past paper questions to build familiarity with different formats, including a persuasive speech, OPVL, short-answer responses, and a 24-mark essay. For the speech on housing standards, I provided detailed feedback on structure, clarity, and linking ideas to broader development indicators, resulting in a moderate score with clear areas for improvement. I then taught OPVL using a water stress map from the World Resources Institute, focusing on writing complete, well-structured answers and clearly distinguishing between origin, purpose, value, and limitation. Moving forward, I helped Batu refine short answers by developing more analytical responses, such as suggesting drip irrigation as a realistic global solution to water stress, and evaluating the impact of water stress on places like Dubai through economic and infrastructural perspectives. Finally, I introduced the 24-mark essay on technological impacts on natural environments, explaining the full marking criteria and ideal structure, and guided him in beginning his response, though he struggled with balance and completing it within time. The remaining essay was assigned as homework, with emphasis on completing all parts and improving structure, analysis, and time management.', 'https://fathom.video/share/F1qLkXk5SunQP7uUyEB9X58dzKrTyUy3'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-05-02'::date, 2, 'N24 timed past paper: labour shortages script and research question justification', 'In this two-hour session, I reviewed Batu''s N24 paper and shifted our approach to a timed, exam-style practice method to better simulate real test conditions and build stamina. As he worked through the paper, I provided live feedback, focusing on improving accuracy and structure. A key discussion was around his Q8 script on labor shortages in the US, where he had misunderstood ''labor'' as white-collar jobs. I clarified that it refers to blue-collar/manual work and guided him to develop more relevant solutions such as increasing minimum wage and introducing flexible immigration policies, while also emphasizing the importance of ending with a clear call to action. We also addressed errors in his research question justification, where he incorrectly explained the topic instead of justifying the choice; I reinforced that a proper justification must include the research question, time frame, and a clear rationale. The session concluded with clear next steps, including completing Q4 and Q9 from the N24 paper and revising the Q8 script using the feedback provided.', 'https://fathom.video/share/JyFx45uftmvq3ygdpBsgCgirU4nhtvzN'),
  ('sneha203btcse24@igdtuw.ac.in', 'Integrated Humanities', 'Subject Group 3: Individuals and Societies', '2026-05-03'::date, 2, 'Exam technique: research question scope, command terms and structured evaluation', 'In this two-hour session, I worked closely with Batu to complete pending questions and strengthen his exam technique ahead of his upcoming Integrated Humanities exam. We focused on identifying meaningful limitations in research, such as short timeframes, and ensuring research question accurately match the scope of the investigation. I guided him to refine overly broad questions into precise ones. We also worked on reinforcing the importance of structured evaluation in long answers. A key part of the session was improving his understanding of command terms, especially ''outline,'' where I emphasized the need for brief explanation rather than simple identification. I also introduced a clear framework for research question justification, stressing the importance of starting with background context before stating the question and explaining its purpose. After reviewing his recent score (56/100), I set a realistic target of 66+ and encouraged consistent practice before his exam. The session concluded with clear next steps, including completing additional questions for feedback and maintaining momentum to improve performance.', 'https://fathom.video/share/FUsBdhHaHsanZKBLw9oMt4hxaKGLC33u'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2025-12-30'::date, 1, 'Logairthms', 'Solve numerical on the topic', 'https://fathom.video/share/FKwxRU2YLQhFgLhKyqXSE-yUcyjcVmsv'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-01-01'::date, 1, 'Logairthms & Quadratic equations', 'Revise log and discussed QE', 'https://fathom.video/share/iLFbxjD6a3MxgiwmrZF5Nh6fpWA34R3k'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-01-17'::date, 1, 'Quadratic equations & its solving methods', 'Solved numerical using formula & completing square method', 'https://fathom.video/share/nCKYxbfNWxhzQMerBz13zooXG9SbGLxw'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-01-31'::date, 1, 'Trigonometry', 'Concept of Trigonometric functions & model', 'https://fathom.video/share/gdqbSjF8mgfyyPSDL-suMafxyVBhVUeh'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-02-02'::date, 1, 'Probability', 'Concpet & numerical of Venn diangram and independent events', 'https://fathom.video/share/qgGLDuBzQiR7ZYVh5cxf3B6z2LdUfvL_'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-02-06'::date, 1, 'Geometry', 'Numerical on 3D shapes', 'https://fathom.video/share/zkCR2Jgzz4WN2typqybWixEiy1PDkRC6'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-02-07'::date, 1, 'Geometry', 'Numerical on 3D shapes', 'https://fathom.video/share/7wyg3Z7KPmM_xJ244kjFymFyetEayz_m'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-02-09'::date, 1, 'Proportionality & circle theorem', 'Solved numerical on said topics', 'https://fathom.video/share/KJpsmDKfSIZl3X67IOJFGLRKhVab1i.1'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-02-21'::date, 1, 'Quadratic factorization', 'Solved numerical based on splitting the middle term of quadratic expressions', 'https://fathom.video/share/shP4qSZ7fhheJcF6RUisaES8zVqjyLdj'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-02-28'::date, 1, 'Quadratic factorization', 'Numerical on Algebraic fractions based on Quadratic expressions', 'https://fathom.video/share/MNN7eYA1xRtj7LH3QKW6K83MSKsdXbN7'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-03-07'::date, 1, 'Combination', 'Dicussed on combinations', 'https://fathom.video/share/H4oc288LrexUzTKa4CfKXFuza3E6n62g'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-03-14'::date, 1, 'Criteria-B: Patterns', 'Solved numericals on pattern based on Criteria B', 'https://fathom.video/share/_s6apAS-8y8t-zqEE9p8gjfcnW1rKsHU'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-03-21'::date, 1, 'Criteria-B: Patterns', 'Solved numerical based on Log, Q.E & sequence in investigating pattern', 'https://fathom.video/share/6HuQJQvzDVJpv-63oMRZ79TRfTTr4sGn'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-03-28'::date, 2, 'Sequences & Criteria-B', 'Solved numerical on Criteria-B connecting quadratic identity along with cubic & quartic sequence.', 'https://fathom.video/share/poLgv2KsSsP36K3hFeyh9krC6MxwRvgD'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-04'::date, 2, 'Quadratic equations & trigoometry', 'Miscellaneous question on quadratic equations, trigonomery', 'https://fathom.video/share/pKZU9nCTkaaCpjGaEuF3Tp_wpMtqsdY3'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-11'::date, 1.5, 'Criteria- A & B', 'solved numerical on algebra, numbers & trigonometry based on said criteria', 'https://fathom.video/share/9LFUd9J9XeJVs7NY_U45SEyJssKEPwYi'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-12'::date, 1.5, 'Criteria- A & B', 'solved numerical on numbers & trigonometry based on criteria A & C', 'https://fathom.video/share/D1paA1wgGcsGKpW3_sMpaibF3oifBHux'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-18'::date, 1.5, 'Criteria- A & C', 'Solved numerical on Venn diagram, probability and inequalities', 'https://fathom.video/share/MDqdYht3dUavsj_ZcJZMybgZ2aowA77S'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-19'::date, 1.5, 'Criteria- A, C & D', 'solved numerical on Trigo, Circle theorem and geometry', 'https://fathom.video/share/mtMt6osvEFxEmm3th8N-RLuizRffpexQ'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-22'::date, 1, 'Similarity and statistics', 'solved numerical based on similarity & central tendency of data connecting Criteria C', 'https://fathom.video/share/cwuiQJLoBL66L-cD6bk7ayixyBr3z93y'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-25'::date, 1.5, 'Statistics', 'Solved numercal on descrete and continuous data along with analysis of CF curve', 'https://fathom.video/share/_sF5h5wsPBZktVFjfwxd9bzxV9hb8q3N'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-26'::date, 1.5, 'Statistics, surds & functions', 'Solved numerical on scatter graph & its analysis, simplification of surds, and basic functions', 'https://fathom.video/share/zWX2zYAy-EUvGzzk4sbvFM4Xqv4BZKXR'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-04-29'::date, 1, 'Functions & transformations', 'Solved numerical on functions, inverse functions and base of transfromations', 'https://fathom.video/share/kkV85hCchsRx7xW7wZio6NsZvoEDy94e'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-05-02'::date, 1, 'Functions & transformations', 'Solved numerical based on transformation of functions', 'https://fathom.video/share/S6N9NsbGsjiBxbDJsy2Q9yF1cW28vRfz'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-05-03'::date, 1.5, 'Functions & transformations', 'Solved numerical related to Criteria B, C & D', 'https://fathom.video/share/yqJ9wHZfGxyZjssagz-UD23BZka1kzv9'),
  ('bharat@ascendnow.info', 'Extended Mathematics', 'Subject Group 5: Mathematics', '2026-05-06'::date, 1, 'Functions & transformations', 'Miscelleneous qoestions based on criteria with different topics', 'https://fathom.video/share/cpN68KiNBwKv4FyfPL55a7j-wnQa9KkJ'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-02-01'::date, 1, 'Level review, goal setting and conjugation', 'Discussing his level and experience learning Spanish, setting goals, conjugation practice', 'https://fathom.video/share/tBGQFRW_Ls2j6GYbkTBxpuiqg_nP4fBv'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-02-07'::date, 1, 'Conjugation and reading', 'Conjugation and reading practice', 'https://fathom.video/share/Jo8nrJkzRQoxcK7P_T5tjLswSdBN63rE'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-02-08'::date, 1, 'Reading and writing', 'Reading and writing practice', 'https://fathom.video/share/9z4LJJeHNAtRaEsWp-BndscjCwfhu2qy'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-02-21'::date, 1, 'Conjugation', 'Conjugation', 'https://fathom.video/share/j8Je-NKmVXGapw4mzstSgbGdLdJ19G4o'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-02-28'::date, 1, 'Conjugation and listening', 'Conjugation practice and listening practice', 'https://fathom.video/share/eJYs9Szqozv9e52fFzPFyDJxWHxb5Faf'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-03-07'::date, 1, 'Conjugation', 'Conjugation practice', 'https://fathom.video/share/8vBoitCZDyxJS-ibCWdJTZYUzVKZwUVC'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-03-14'::date, 1, 'Conjugation and listening', 'Conjugation practice and listening practice', 'https://fathom.video/share/zGY1LBZuxJYV19mcLsmBeuQxEw5WeyQN'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-03-21'::date, 1, 'Reading comprehension', 'Reading comprehension', 'https://fathom.video/share/yn3pWcMvefV-zd5o8_upRmhv_3dsj4aa'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-03-28'::date, 1, 'Writing and listening comprehension', 'Writing and listening comprehension', 'https://fathom.video/share/voafpNUWCPuTovc7ZBgew4zpMQNmz1T5'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-03-29'::date, 1, 'Listening comprehension', 'Listening comprehension', 'https://fathom.video/share/X9fyRsDabKtQX4xKSQWUexR7dhcTHzRP'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-04-04'::date, 2, 'Conjugation and reading comprehension', 'Conjugation and Reading comprehension', 'https://fathom.video/share/m8wJp6NdZw2vVF2q8pERAtJDLzQuKtLG'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-04-11'::date, 1, 'Conjugation and reading comprehension', 'Conjugation and Reading comprehension', 'https://fathom.video/share/VgfJt7o4G9uS35FeiXy4WXNAhzzgmV6Q'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-04-18'::date, 1, 'Listening practice', 'Listening practice', 'https://fathom.video/share/1-oAKsE7CwwDCGsWhGz2wo91bXtQpozK'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-04-25'::date, 1, 'Reading comprehension', 'Reading comprehension', 'https://fathom.video/share/Xye3_zNsPx3uTx3n7zM6u47UJg6A9BNn'),
  ('ylenia@ascendnow.info', 'Spanish', 'Subject Group 2: Language Acquisition', '2026-04-25'::date, 1, 'Reading comprehension, grammar and writing', 'Reading comprehension, grammar, writing', 'https://fathom.video/share/vViR2oXfewRrGayyrvpn6nZNHxCxtb_o'),
  ('magdaleina@ascendnow.info', 'Personal Project', 'Core Requirements', '2025-12-31'::date, 1, 'Personal Project', 'MYP Personal Project', 'https://fathom.video/share/TeXiDJrVYzyPb9bamwwLzFewsBeXxkQM'),
  ('magdaleina@ascendnow.info', 'Personal Project', 'Core Requirements', '2026-01-12'::date, 1, 'Personal Project report', 'PP report', 'https://fathom.video/share/KVHMrpnwb9JZxxpc2ToixiraGjmHH6M2'),
  ('magdaleina@ascendnow.info', 'English', 'Subject Group 1: Language and Literature', '2026-02-02'::date, 1, 'Writing', 'Writing', 'https://fathom.video/share/dsoDegGruToscUuKyiyyx7ASy5SboVZe'),
  ('jesse@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-02-08'::date, 1.25, 'Biology revision', 'bio revision', 'https://fathom.video/share/ajvZHBafobx8pSufLwmpHirzvyVR4-8w'),
  ('jesse@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-04-19'::date, 1, 'Past papers, 2019/2020', 'past papers, 2019/2020', 'https://fathom.video/share/Tas8W12yxWZCdZHsfyRgj_jMAsxveTY8'),
  ('sajjad@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-02-03'::date, 1, 'Prokaryotes and Eukaryotes', 'Prokaryotes and Eukaryotes.', 'https://fathom.video/share/QgEaHa6xMWJzHsAzLVoM8sLwSBxPHrdN'),
  ('sajjad@ascendnow.info', 'Chemistry', 'Subject Group 4: Sciences', '2026-04-25'::date, 1, 'Criteria A and B', 'Criteria A and B', 'https://fathom.video/share/wskCNhxzYePY4X4acFF9ktq3SHJsZvKJ'),
  ('sajjad@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-04-26'::date, 1, 'Past Papers', 'Past Papers', 'https://fathom.video/share/2UyD_GzZqTik1gkDuxZN8w-Xbo84x_oN'),
  ('sajjad@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-05-02'::date, 1, 'Criteria C & D', 'Crit- C & D', 'https://fathom.video/share/jW8GATLEuT2qnh_5NfC3Z1fAMNzTuqpG'),
  ('sajjad@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-05-03'::date, 1, 'Concept class', 'Concept class', 'https://fathom.video/share/bxKfFT9wA_USwW-_9uzVMqoUx28zuwf1'),
  ('sajjad@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-05-09'::date, 1, 'Biology revision', 'Biology revision', 'https://fathom.video/share/QBmJa57vJbQxzQoAvkLusDTY_YruWsTe'),
  ('sajjad@ascendnow.info', 'Integrated Sciences', 'Subject Group 4: Sciences', '2026-05-10'::date, 2, 'Whole curriculum revision', 'Whole curriculum revision', 'https://fathom.video/share/4aP5CyMAzac3fMdv9cCQJakeW5pGxfaj')
) as v(teacher_email, subject_name, group_name, session_date, duration_hrs, topic, summary, video_link)
join public.teachers t on t.email = v.teacher_email
join public.curricula c on c.name = 'IBMYP'
join public.curriculum_groups g on g.curriculum_id = c.id and g.name = v.group_name
join public.subjects s on s.curriculum_group_id = g.id and s.name = v.subject_name
join public.course_types ct on ct.name = 'Academic'
join public.program_types pt on pt.name = 'Academics' and pt.parent_id is null
join public.teachers pc on pc.email = 'rana.walid@ascendnow.info'
join public.students st on st.email = 'snehagupta161006@gmail.com';
