-- Ascend Now — baseline full schema
--
-- This is a single, consolidated migration that reproduces the live Ascend
-- Now database (project ref uqyuczvckqxgtilpzarh) exactly as of 2026-07-01,
-- generated by direct introspection of the live database rather than by
-- replaying history. It replaces two previous, mutually-inconsistent change
-- logs (db/schema/*.sql — 28 numbered files, and the prior contents of
-- supabase/migrations/ — 35 timestamped files) whose own migration-tracking
-- table was empty, meaning they could no longer be trusted as an accurate
-- record of what was actually live. See db/docs/VERIFIED_DATABASE_STATE.md
-- for full narrative context and the exact live data this was derived from.
--
-- This migration is schema-only — it does not restore data (subjects,
-- teachers, students, seed rows for program_types/course_types/curricula,
-- etc.). Run db/scripts/ as needed after applying this to seed lookup data
-- and create your first admin.
--
-- This migration reproduces one known issue that was present in the live
-- database at the time of this snapshot: `zoom_invoices` had no
-- SELECT/INSERT/UPDATE/DELETE grants for `authenticated`, despite RLS
-- policies assuming teachers could insert/read their own rows (see section
-- 13). That gap was confirmed and fixed live immediately after this file
-- was written — see 20260701000001_fix_zoom_invoices_authenticated_grant.sql.
-- Left as-is here (rather than rewritten) since this file is a point-in-time
-- snapshot; anyone applying this baseline from scratch should also apply
-- the follow-up migration.

-- =========================================================================
-- 1. Enum types
-- =========================================================================

CREATE TYPE public.user_role AS ENUM ('teacher', 'student', 'parent', 'performance_coach', 'admin');
CREATE TYPE public.engagement_rating AS ENUM ('low', 'medium', 'high');

-- =========================================================================
-- 2. Sequences (only the two columns that are not IDENTITY columns)
-- =========================================================================

CREATE SEQUENCE public.students_num_seq;
CREATE SEQUENCE public.zoom_invoices_id_seq;

-- =========================================================================
-- 3. Tables (foreign keys added separately in section 5, to avoid ordering
--    problems — every table below only has PRIMARY KEY / UNIQUE / CHECK /
--    DEFAULT constraints inline)
-- =========================================================================

CREATE TABLE public.users (
  id uuid PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text NOT NULL,
  full_name text,
  role public.user_role NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  avatar_url text
);

CREATE TABLE public.teachers (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  first_name text NOT NULL,
  last_name text,
  country text,
  email text UNIQUE,
  phone_number text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid,
  is_performance_coach boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE public.teacher_subjects (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  teacher_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  subject_id smallint NOT NULL,
  curriculum_id smallint
);

CREATE TABLE public.admins (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.students (
  id text PRIMARY KEY DEFAULT ('S' || (nextval('public.students_num_seq'))::text),
  first_name text NOT NULL,
  last_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  parent_full_name text,
  phone_number text,
  email text,
  address text,
  country text
);

CREATE TABLE public.pc_student_assignments (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id text NOT NULL,
  pc_teacher_id bigint NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  unassigned_at timestamptz
);

CREATE TABLE public.program_types (
  id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  parent_id smallint,
  type text
);

CREATE TABLE public.course_types (
  id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  color text NOT NULL DEFAULT 'slate',
  sort_order smallint NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.subject_categories (
  id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT subject_categories_type_check CHECK (type = ANY (ARRAY['academic'::text, 'beyond_academic'::text]))
);

CREATE TABLE public.curricula (
  id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  sort_order smallint NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  added_by_teacher_id integer,
  acknowledged_by_user_id uuid,
  acknowledged_at timestamptz
);

CREATE TABLE public.curriculum_groups (
  id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  curriculum_id smallint NOT NULL,
  name text NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.subjects (
  id smallint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  sort_order smallint NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  category_id smallint,
  added_by_teacher_id integer,
  acknowledged_by_user_id uuid,
  acknowledged_at timestamptz,
  curriculum_group_id smallint,
  board text,
  subject_code text,
  level text
);

CREATE TABLE public.session_logs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_first_name text,
  student_last_name text,
  session_date date NOT NULL,
  session_duration_hrs numeric,
  program_type_id smallint,
  topic text,
  video_link text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  coordinator_teacher_id bigint,
  teacher_id bigint,
  subject_id smallint,
  curriculum_id smallint,
  student_id text,
  no_show_type text,
  fathom_summary text,
  fathom_summary_doc_url text,
  independent_work text[] DEFAULT '{}'::text[],
  engagement_rating public.engagement_rating,
  performance_feedback text,
  flag_for_coach boolean NOT NULL DEFAULT false,
  flag_category text,
  flag_comments text,
  course_type_id smallint,
  invoice_file_url text,
  CONSTRAINT session_logs_session_duration_hrs_check CHECK (session_duration_hrs >= 0::numeric AND (session_duration_hrs * 4::numeric) = round(session_duration_hrs * 4::numeric)),
  CONSTRAINT session_logs_no_show_type_check CHECK (no_show_type = ANY (ARRAY['no_show_1'::text, 'no_show_2'::text, 'no_show_plus'::text]))
);

CREATE TABLE public.student_packages (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id text NOT NULL,
  program_type_id smallint,
  total_hours_purchased numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  course_type_id smallint,
  status text NOT NULL DEFAULT 'active',
  closed_at timestamptz,
  CONSTRAINT student_packages_total_hours_purchased_check CHECK (total_hours_purchased >= 0::numeric),
  CONSTRAINT student_packages_status_check CHECK (status = ANY (ARRAY['active'::text, 'closed'::text])),
  CONSTRAINT student_packages_student_id_course_type_id_key UNIQUE (student_id, course_type_id)
);

CREATE TABLE public.package_topups (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_package_id bigint NOT NULL,
  hours_added numeric NOT NULL,
  package_size_label text NOT NULL,
  note text,
  added_by_user_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT package_topups_hours_added_check CHECK (hours_added > 0::numeric)
);

CREATE TABLE public.invoices (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  student_id text NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  generated_by_user_id uuid NOT NULL,
  total_hours numeric NOT NULL DEFAULT 0,
  doc_url text,
  status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  locked_at timestamptz,
  locked_by_user_id uuid,
  CONSTRAINT invoices_status_check CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'locked'::text]))
);

CREATE TABLE public.invoice_line_items (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL,
  teacher_id bigint,
  subject_id smallint,
  curriculum_id smallint,
  hours numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  session_count integer NOT NULL DEFAULT 0
);

CREATE TABLE public.invoice_packages (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL,
  student_package_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT invoice_packages_invoice_id_student_package_id_key UNIQUE (invoice_id, student_package_id)
);

CREATE TABLE public.monthly_reports (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  year smallint NOT NULL,
  month smallint NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  locked_at timestamptz,
  locked_by_user_id uuid,
  period_start date NOT NULL,
  period_end date NOT NULL,
  total_hours numeric NOT NULL DEFAULT 0,
  total_sessions integer NOT NULL DEFAULT 0,
  unique_students integer NOT NULL DEFAULT 0,
  no_show_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  generated_at timestamptz NOT NULL DEFAULT now(),
  generated_by_user_id uuid,
  CONSTRAINT monthly_reports_month_check CHECK (month >= 1 AND month <= 12),
  CONSTRAINT monthly_reports_status_check CHECK (status = ANY (ARRAY['draft'::text, 'locked'::text])),
  CONSTRAINT monthly_reports_year_month_key UNIQUE (year, month)
);

CREATE TABLE public.monthly_report_teacher_stats (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL,
  teacher_id bigint,
  teacher_name text,
  sessions integer NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0
);

CREATE TABLE public.monthly_report_student_stats (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL,
  student_id text,
  student_name text,
  sessions integer NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0
);

CREATE TABLE public.monthly_report_teacher_subject_stats (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL,
  teacher_id bigint,
  teacher_name text,
  subject_id smallint,
  subject_name text,
  subject_level text,
  curriculum_id smallint,
  curriculum_name text,
  program_type_name text,
  sessions integer NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0
);

CREATE TABLE public.monthly_report_student_subject_stats (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL,
  student_id text,
  student_name text,
  subject_id smallint,
  subject_name text,
  subject_level text,
  curriculum_id smallint,
  curriculum_name text,
  sessions integer NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0
);

CREATE TABLE public.monthly_report_subject_stats (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL,
  subject_id smallint,
  subject_name text,
  subject_level text,
  curriculum_id smallint,
  curriculum_name text,
  sessions integer NOT NULL DEFAULT 0,
  hours numeric NOT NULL DEFAULT 0
);

CREATE TABLE public.zoom_invoices (
  id bigint PRIMARY KEY DEFAULT nextval('public.zoom_invoices_id_seq'),
  teacher_id bigint NOT NULL,
  period_month date NOT NULL,
  file_url text NOT NULL,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  uploaded_by_user_id uuid,
  status text NOT NULL DEFAULT 'pending',
  acknowledged_at timestamptz,
  acknowledged_by_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT zoom_invoices_status_check CHECK (status = ANY (ARRAY['pending'::text, 'acknowledged'::text])),
  CONSTRAINT zoom_invoices_teacher_id_period_month_key UNIQUE (teacher_id, period_month)
);

ALTER SEQUENCE public.zoom_invoices_id_seq OWNED BY public.zoom_invoices.id;

-- =========================================================================
-- 4. auth.users FK note
--    `public.users.id` references `auth.users.id` (Supabase-managed schema).
-- =========================================================================

-- =========================================================================
-- 5. Foreign keys
-- =========================================================================

ALTER TABLE public.users ADD CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.teachers ADD CONSTRAINT teachers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE public.teacher_subjects ADD CONSTRAINT teacher_subjects_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id) ON DELETE CASCADE;
ALTER TABLE public.teacher_subjects ADD CONSTRAINT teacher_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE;
ALTER TABLE public.teacher_subjects ADD CONSTRAINT teacher_subjects_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id) ON DELETE CASCADE;

ALTER TABLE public.admins ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE public.pc_student_assignments ADD CONSTRAINT pc_student_assignments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.pc_student_assignments ADD CONSTRAINT pc_student_assignments_pc_teacher_id_fkey FOREIGN KEY (pc_teacher_id) REFERENCES public.teachers(id);

ALTER TABLE public.program_types ADD CONSTRAINT program_types_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.program_types(id);

ALTER TABLE public.curricula ADD CONSTRAINT curricula_added_by_teacher_id_fkey FOREIGN KEY (added_by_teacher_id) REFERENCES public.teachers(id);
ALTER TABLE public.curricula ADD CONSTRAINT curricula_acknowledged_by_user_id_fkey FOREIGN KEY (acknowledged_by_user_id) REFERENCES auth.users(id);

ALTER TABLE public.curriculum_groups ADD CONSTRAINT curriculum_groups_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id) ON DELETE RESTRICT;

ALTER TABLE public.subjects ADD CONSTRAINT subjects_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.subject_categories(id);
ALTER TABLE public.subjects ADD CONSTRAINT subjects_curriculum_group_id_fkey FOREIGN KEY (curriculum_group_id) REFERENCES public.curriculum_groups(id);
ALTER TABLE public.subjects ADD CONSTRAINT subjects_added_by_teacher_id_fkey FOREIGN KEY (added_by_teacher_id) REFERENCES public.teachers(id);
ALTER TABLE public.subjects ADD CONSTRAINT subjects_acknowledged_by_user_id_fkey FOREIGN KEY (acknowledged_by_user_id) REFERENCES auth.users(id);

ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_program_type_id_fkey FOREIGN KEY (program_type_id) REFERENCES public.program_types(id);
ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE SET NULL;
ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_course_type_id_fkey FOREIGN KEY (course_type_id) REFERENCES public.course_types(id);
ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id) ON DELETE SET NULL;
ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_coordinator_teacher_id_fkey FOREIGN KEY (coordinator_teacher_id) REFERENCES public.teachers(id);
ALTER TABLE public.session_logs ADD CONSTRAINT session_logs_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);

ALTER TABLE public.student_packages ADD CONSTRAINT student_packages_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.student_packages ADD CONSTRAINT student_packages_program_type_id_fkey FOREIGN KEY (program_type_id) REFERENCES public.program_types(id);
ALTER TABLE public.student_packages ADD CONSTRAINT student_packages_course_type_id_fkey FOREIGN KEY (course_type_id) REFERENCES public.course_types(id);

ALTER TABLE public.package_topups ADD CONSTRAINT package_topups_student_package_id_fkey FOREIGN KEY (student_package_id) REFERENCES public.student_packages(id) ON DELETE CASCADE;
ALTER TABLE public.package_topups ADD CONSTRAINT package_topups_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(id);

ALTER TABLE public.invoices ADD CONSTRAINT invoices_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_generated_by_user_id_fkey FOREIGN KEY (generated_by_user_id) REFERENCES public.users(id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_locked_by_user_id_fkey FOREIGN KEY (locked_by_user_id) REFERENCES public.users(id);

ALTER TABLE public.invoice_line_items ADD CONSTRAINT invoice_line_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_line_items ADD CONSTRAINT invoice_line_items_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);
ALTER TABLE public.invoice_line_items ADD CONSTRAINT invoice_line_items_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id);
ALTER TABLE public.invoice_line_items ADD CONSTRAINT invoice_line_items_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id);

ALTER TABLE public.invoice_packages ADD CONSTRAINT invoice_packages_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_packages ADD CONSTRAINT invoice_packages_student_package_id_fkey FOREIGN KEY (student_package_id) REFERENCES public.student_packages(id);

ALTER TABLE public.monthly_reports ADD CONSTRAINT monthly_reports_generated_by_user_id_fkey FOREIGN KEY (generated_by_user_id) REFERENCES public.users(id);
ALTER TABLE public.monthly_reports ADD CONSTRAINT monthly_reports_locked_by_user_id_fkey FOREIGN KEY (locked_by_user_id) REFERENCES public.users(id);

ALTER TABLE public.monthly_report_teacher_stats ADD CONSTRAINT monthly_report_teacher_stats_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.monthly_reports(id) ON DELETE CASCADE;
ALTER TABLE public.monthly_report_teacher_stats ADD CONSTRAINT monthly_report_teacher_stats_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);

ALTER TABLE public.monthly_report_student_stats ADD CONSTRAINT monthly_report_student_stats_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.monthly_reports(id) ON DELETE CASCADE;
ALTER TABLE public.monthly_report_student_stats ADD CONSTRAINT monthly_report_student_stats_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE public.monthly_report_teacher_subject_stats ADD CONSTRAINT monthly_report_teacher_subject_stats_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.monthly_reports(id) ON DELETE CASCADE;
ALTER TABLE public.monthly_report_teacher_subject_stats ADD CONSTRAINT monthly_report_teacher_subject_stats_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);
ALTER TABLE public.monthly_report_teacher_subject_stats ADD CONSTRAINT monthly_report_teacher_subject_stats_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id);
ALTER TABLE public.monthly_report_teacher_subject_stats ADD CONSTRAINT monthly_report_teacher_subject_stats_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id);

ALTER TABLE public.monthly_report_student_subject_stats ADD CONSTRAINT monthly_report_student_subject_stats_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.monthly_reports(id) ON DELETE CASCADE;
ALTER TABLE public.monthly_report_student_subject_stats ADD CONSTRAINT monthly_report_student_subject_stats_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.monthly_report_student_subject_stats ADD CONSTRAINT monthly_report_student_subject_stats_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id);
ALTER TABLE public.monthly_report_student_subject_stats ADD CONSTRAINT monthly_report_student_subject_stats_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id);

ALTER TABLE public.monthly_report_subject_stats ADD CONSTRAINT monthly_report_subject_stats_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.monthly_reports(id) ON DELETE CASCADE;
ALTER TABLE public.monthly_report_subject_stats ADD CONSTRAINT monthly_report_subject_stats_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id);
ALTER TABLE public.monthly_report_subject_stats ADD CONSTRAINT monthly_report_subject_stats_curriculum_id_fkey FOREIGN KEY (curriculum_id) REFERENCES public.curricula(id);

ALTER TABLE public.zoom_invoices ADD CONSTRAINT zoom_invoices_teacher_id_fkey FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);
ALTER TABLE public.zoom_invoices ADD CONSTRAINT zoom_invoices_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES auth.users(id);
ALTER TABLE public.zoom_invoices ADD CONSTRAINT zoom_invoices_acknowledged_by_user_id_fkey FOREIGN KEY (acknowledged_by_user_id) REFERENCES auth.users(id);

-- =========================================================================
-- 6. Additional indexes (beyond the PK/UNIQUE indexes created inline above)
-- =========================================================================

CREATE INDEX idx_admins_user_id ON public.admins USING btree (user_id);

CREATE INDEX idx_teachers_user_id ON public.teachers USING btree (user_id);
CREATE INDEX idx_teachers_name ON public.teachers USING btree (first_name, last_name);
CREATE INDEX idx_teachers_is_performance_coach ON public.teachers USING btree (is_performance_coach);

CREATE INDEX idx_teacher_subjects_teacher ON public.teacher_subjects USING btree (teacher_id);
CREATE INDEX idx_teacher_subjects_subject_id ON public.teacher_subjects USING btree (subject_id);
CREATE UNIQUE INDEX teacher_subjects_academic_uq ON public.teacher_subjects USING btree (teacher_id, subject_id, curriculum_id) WHERE (curriculum_id IS NOT NULL);
CREATE UNIQUE INDEX teacher_subjects_non_academic_uq ON public.teacher_subjects USING btree (teacher_id, subject_id) WHERE (curriculum_id IS NULL);

CREATE INDEX idx_pc_assignments_teacher ON public.pc_student_assignments USING btree (pc_teacher_id);
CREATE UNIQUE INDEX uq_active_pc_per_student ON public.pc_student_assignments USING btree (student_id) WHERE (unassigned_at IS NULL);

CREATE UNIQUE INDEX subjects_name_cat_no_group_idx ON public.subjects USING btree (name, category_id) WHERE (curriculum_group_id IS NULL);

CREATE INDEX idx_session_logs_date ON public.session_logs USING btree (session_date);
CREATE INDEX idx_session_logs_teacher_id ON public.session_logs USING btree (teacher_id);
CREATE INDEX idx_session_logs_coordinator_teacher_id ON public.session_logs USING btree (coordinator_teacher_id);
CREATE INDEX idx_session_logs_program ON public.session_logs USING btree (program_type_id);
CREATE INDEX idx_session_logs_course_type ON public.session_logs USING btree (course_type_id);
CREATE INDEX idx_session_logs_curriculum_id ON public.session_logs USING btree (curriculum_id);
CREATE INDEX idx_session_logs_subject_id ON public.session_logs USING btree (subject_id);
CREATE INDEX idx_session_logs_student ON public.session_logs USING btree (student_first_name, student_last_name);

CREATE INDEX idx_invoices_student_id ON public.invoices USING btree (student_id);
CREATE INDEX idx_invoice_line_items_invoice_id ON public.invoice_line_items USING btree (invoice_id);
CREATE INDEX idx_invoice_packages_invoice_id ON public.invoice_packages USING btree (invoice_id);
CREATE INDEX idx_invoice_packages_student_package_id ON public.invoice_packages USING btree (student_package_id);

CREATE INDEX idx_topups_package_id ON public.package_topups USING btree (student_package_id);

CREATE INDEX idx_monthly_reports_year_month ON public.monthly_reports USING btree (year, month);
CREATE INDEX idx_monthly_report_teacher_stats_report_id ON public.monthly_report_teacher_stats USING btree (report_id);
CREATE INDEX idx_monthly_report_student_stats_report_id ON public.monthly_report_student_stats USING btree (report_id);
CREATE INDEX idx_monthly_report_teacher_subject_stats_report_id ON public.monthly_report_teacher_subject_stats USING btree (report_id);
CREATE INDEX idx_monthly_report_student_subject_stats_report_id ON public.monthly_report_student_subject_stats USING btree (report_id);
CREATE INDEX idx_monthly_report_subject_stats_report_id ON public.monthly_report_subject_stats USING btree (report_id);

CREATE INDEX idx_zoom_invoices_teacher ON public.zoom_invoices USING btree (teacher_id);
CREATE INDEX idx_zoom_invoices_period ON public.zoom_invoices USING btree (period_month);

-- =========================================================================
-- 7. Table & column comments
-- =========================================================================

COMMENT ON TABLE public.users IS 'Central identity table, 1-to-1 with auth.users. PASSWORDS ARE NOT STORED HERE — Supabase Auth (auth.users) handles password hashing and verification. Role-specific fields live in teachers / students / etc., linked via user_id.';
COMMENT ON TABLE public.admins IS 'Minimal admin profile, linked to public.users. Admins manage all data; access control comes from users.role = ''admin'', not from anything stored here.';

COMMENT ON COLUMN public.teachers.user_id IS 'Links this teacher profile to their login identity in public.users.';
COMMENT ON COLUMN public.teachers.last_name IS 'Nullable — most rows in source sheet had no surname recorded.';
COMMENT ON COLUMN public.teachers.is_performance_coach IS 'True if this teacher also coordinates sessions (acts as a performance coach). Not a separate role/table — a teacher with extra responsibility.';
COMMENT ON COLUMN public.session_logs.teacher_id IS 'The teacher who taught this session. Auto-filled by the frontend from the logged-in teacher''s profile — never typed manually.';
COMMENT ON COLUMN public.session_logs.coordinator_teacher_id IS 'The performance coach who coordinated this session — actually a teacher row (one with is_performance_coach = true, though this is not DB-enforced). Replaces the old free-text coordinator column.';

-- =========================================================================
-- 8. Functions
-- =========================================================================

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select exists (
    select 1 from public.users
    where id = auth.uid() and role = 'admin'
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_performance_coach()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select exists (
    select 1 from public.users
    where id = auth.uid() and role = 'performance_coach'
  )
$function$;

CREATE OR REPLACE FUNCTION public.my_teacher_id()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select id from public.teachers
  where user_id = auth.uid()
  limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.get_email_for_username(p_username text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  select email from public.users where username = p_username limit 1;
$function$;

CREATE OR REPLACE FUNCTION public.create_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
    insert into public.users (id, username, email, full_name, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'username', new.email),
        new.email,
        new.raw_user_meta_data ->> 'full_name',
        coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'student'::public.user_role)
    );
    return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_teacher_profile(p_user_id uuid, p_country text, p_subjects text[])
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
    v_teacher_id bigint;
    v_subject text;
begin
    insert into teachers (user_id, first_name, last_name, country, email, phone_number)
    select
        p_user_id,
        u.full_name,   -- simplest for now; split into first/last later if needed
        null,
        p_country,
        u.email,
        null
    from public.users u
    where u.id = p_user_id
    returning id into v_teacher_id;

    foreach v_subject in array p_subjects
    loop
        insert into teacher_subjects (teacher_id, subject_name)
        values (v_teacher_id, v_subject)
        on conflict (teacher_id, subject_name) do nothing;
    end loop;

    return v_teacher_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_admin_profile(p_user_id uuid)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
    v_admin_id bigint;
begin
    insert into admins (user_id)
    values (p_user_id)
    returning id into v_admin_id;

    return v_admin_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.sync_teacher_pc_role()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if NEW.user_id is not null then
    update public.users
    set role = case
      when NEW.is_performance_coach then 'performance_coach'::public.user_role
      else 'teacher'::public.user_role
    end
    where id = NEW.user_id;
  end if;
  return NEW;
end;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_self_privilege_escalation()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  if exists (
    select 1 from public.users
    where id = auth.uid() and role = 'admin'
  ) then
    return new;
  end if;
  if new.role is distinct from old.role then
    raise exception 'Changing role is not allowed';
  end if;
  if new.is_active is distinct from old.is_active then
    raise exception 'Changing active status is not allowed';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_session_log_change_in_locked_month()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  old_locked boolean := false;
  new_locked boolean := false;
BEGIN
  -- Editing or deleting a row that already belongs to a locked month is
  -- blocked regardless of what's changing (checked against OLD).
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    SELECT EXISTS (
      SELECT 1 FROM public.monthly_reports mr
      WHERE mr.status = 'locked'
        AND mr.year  = EXTRACT(YEAR FROM OLD.session_date)::smallint
        AND mr.month = EXTRACT(MONTH FROM OLD.session_date)::smallint
    ) INTO old_locked;
  END IF;

  -- Inserting a new row, or moving an existing one, into a locked month is
  -- just as much a change to that month's frozen data (checked against NEW).
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    SELECT EXISTS (
      SELECT 1 FROM public.monthly_reports mr
      WHERE mr.status = 'locked'
        AND mr.year  = EXTRACT(YEAR FROM NEW.session_date)::smallint
        AND mr.month = EXTRACT(MONTH FROM NEW.session_date)::smallint
    ) INTO new_locked;
  END IF;

  IF old_locked THEN
    RAISE EXCEPTION 'Cannot % this session log — % is a locked report month.',
      lower(TG_OP), to_char(OLD.session_date, 'Mon YYYY');
  END IF;

  IF new_locked THEN
    RAISE EXCEPTION 'Cannot % this session log into % — that report month is locked.',
      lower(TG_OP), to_char(NEW.session_date, 'Mon YYYY');
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_locked_monthly_report_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF OLD.status = 'locked' THEN
    RAISE EXCEPTION 'Cannot modify a locked monthly report.';
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_locked_monthly_report_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF OLD.status = 'locked' THEN
    RAISE EXCEPTION 'Cannot delete a locked monthly report — it also protects that month''s session logs from editing.';
  END IF;
  RETURN OLD;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_locked_report_stat_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  parent_status text;
BEGIN
  SELECT status INTO parent_status FROM public.monthly_reports WHERE id = OLD.report_id;
  IF parent_status = 'locked' THEN
    RAISE EXCEPTION 'Cannot modify stats for a locked monthly report.';
  END IF;
  RETURN OLD;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_locked_invoice_delete()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF OLD.status = 'locked' THEN
    RAISE EXCEPTION 'Cannot delete a locked invoice';
  END IF;
  RETURN OLD;
END;
$function$;

CREATE OR REPLACE FUNCTION public.on_package_topup_inserted()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE public.student_packages
  SET
    total_hours_purchased = total_hours_purchased + NEW.hours_added,
    updated_at            = now()
  WHERE id = NEW.student_package_id;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
    new.updated_at = now();
    return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.touch_invoices_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.touch_student_packages_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.touch_package_allocations_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

-- =========================================================================
-- 9. Triggers
-- =========================================================================

CREATE TRIGGER trg_create_user_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_user_profile();

CREATE TRIGGER trg_prevent_privilege_escalation BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.prevent_self_privilege_escalation();
CREATE TRIGGER trg_touch_users BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TRIGGER trg_sync_teacher_pc_role AFTER INSERT OR UPDATE OF is_performance_coach ON public.teachers FOR EACH ROW EXECUTE FUNCTION public.sync_teacher_pc_role();
CREATE TRIGGER trg_touch_teachers BEFORE UPDATE ON public.teachers FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TRIGGER trg_touch_admins BEFORE UPDATE ON public.admins FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TRIGGER trg_prevent_session_log_change_in_locked_month BEFORE INSERT OR DELETE OR UPDATE ON public.session_logs FOR EACH ROW EXECUTE FUNCTION public.prevent_session_log_change_in_locked_month();
CREATE TRIGGER trg_touch_session_logs BEFORE UPDATE ON public.session_logs FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE TRIGGER trg_touch_student_packages_updated_at BEFORE UPDATE ON public.student_packages FOR EACH ROW EXECUTE FUNCTION public.touch_student_packages_updated_at();

CREATE TRIGGER trg_package_topup_update_hours AFTER INSERT ON public.package_topups FOR EACH ROW EXECUTE FUNCTION public.on_package_topup_inserted();

CREATE TRIGGER trg_touch_invoices_updated_at BEFORE UPDATE ON public.invoices FOR EACH ROW EXECUTE FUNCTION public.touch_invoices_updated_at();
CREATE TRIGGER trg_prevent_locked_invoice_delete BEFORE DELETE ON public.invoices FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_invoice_delete();

CREATE TRIGGER trg_prevent_locked_monthly_report_update BEFORE UPDATE ON public.monthly_reports FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_monthly_report_update();
CREATE TRIGGER trg_prevent_locked_monthly_report_delete BEFORE DELETE ON public.monthly_reports FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_monthly_report_delete();

CREATE TRIGGER trg_prevent_locked_teacher_stat_change BEFORE DELETE OR UPDATE ON public.monthly_report_teacher_stats FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_report_stat_change();
CREATE TRIGGER trg_prevent_locked_student_stat_change BEFORE DELETE OR UPDATE ON public.monthly_report_student_stats FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_report_stat_change();
CREATE TRIGGER trg_prevent_locked_teacher_subject_stat_change BEFORE DELETE OR UPDATE ON public.monthly_report_teacher_subject_stats FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_report_stat_change();
CREATE TRIGGER trg_prevent_locked_student_subject_stat_change BEFORE DELETE OR UPDATE ON public.monthly_report_student_subject_stats FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_report_stat_change();
CREATE TRIGGER trg_prevent_locked_subject_stat_change BEFORE DELETE OR UPDATE ON public.monthly_report_subject_stats FOR EACH ROW EXECUTE FUNCTION public.prevent_locked_report_stat_change();

-- Event trigger: automatically enables RLS on any new table created in
-- `public` from now on (fail-closed default — a new table is fully locked,
-- including to admins, until policies are added). Not something anyone
-- deliberately designed — appears to be a Supabase project default — but
-- reproduced here since it is genuinely active on the live project.
CREATE EVENT TRIGGER ensure_rls ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION public.rls_auto_enable();

-- =========================================================================
-- 10. Row Level Security — enable on all tables
-- =========================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pc_student_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subject_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curricula ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curriculum_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_topups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_report_teacher_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_report_student_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_report_teacher_subject_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_report_student_subject_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_report_subject_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zoom_invoices ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 11. Row Level Security — policies
--
-- Reproduced exactly as found live, INCLUDING duplicate/overlapping
-- policies that are functionally redundant (e.g. two INSERT policies on
-- session_logs implementing the same check two different ways). These are
-- leftovers from iterative migrations, not something introduced here — see
-- db/docs/VERIFIED_DATABASE_STATE.md for the full list and a note that
-- consolidating them is a worthwhile follow-up, done deliberately rather
-- than silently in this baseline.
-- =========================================================================

-- users
CREATE POLICY "Admins can do everything on users" ON public.users FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Performance coaches can read users" ON public.users FOR SELECT USING (public.is_performance_coach());
CREATE POLICY "Users can read their own row" ON public.users FOR SELECT USING (id = auth.uid());
CREATE POLICY "Users can update their own row" ON public.users FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- teachers
CREATE POLICY "Admins can do everything on teachers" ON public.teachers FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Any authenticated user can read teacher names" ON public.teachers FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Any logged-in user can read performance coaches" ON public.teachers FOR SELECT USING (is_performance_coach = true AND auth.uid() IS NOT NULL);
CREATE POLICY "Teachers can read their own row" ON public.teachers FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Teachers can update their own teacher profile" ON public.teachers FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- teacher_subjects
CREATE POLICY "Admins can do everything on teacher_subjects" ON public.teacher_subjects FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all teacher_subjects" ON public.teacher_subjects FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role));
CREATE POLICY "Teachers can delete their own subjects" ON public.teacher_subjects FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.teachers WHERE teachers.id = teacher_subjects.teacher_id AND teachers.user_id = auth.uid()));
CREATE POLICY "Teachers can insert their own subjects" ON public.teacher_subjects FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.teachers WHERE teachers.id = teacher_subjects.teacher_id AND teachers.user_id = auth.uid()));
CREATE POLICY "Teachers can read their own subjects" ON public.teacher_subjects FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.teachers WHERE teachers.id = teacher_subjects.teacher_id AND teachers.user_id = auth.uid()));

-- admins
CREATE POLICY "Admins can do everything on admins" ON public.admins FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- students
CREATE POLICY "Authenticated users can insert students" ON public.students FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated users can read students" ON public.students FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can update students" ON public.students FOR UPDATE TO authenticated USING (true);

-- pc_student_assignments
CREATE POLICY "admin_all_pc_assignments" ON public.pc_student_assignments FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "pc_assign_unassigned_student_to_self" ON public.pc_student_assignments FOR INSERT
  WITH CHECK (public.is_performance_coach() AND pc_teacher_id = public.my_teacher_id()
    AND NOT EXISTS (SELECT 1 FROM public.pc_student_assignments existing WHERE existing.student_id = pc_student_assignments.student_id AND existing.unassigned_at IS NULL));
CREATE POLICY "pc_read_own_assignments" ON public.pc_student_assignments FOR SELECT
  USING (public.is_performance_coach() AND pc_teacher_id = public.my_teacher_id());
CREATE POLICY "pc_unassign_own_students" ON public.pc_student_assignments FOR UPDATE
  USING (public.is_performance_coach() AND pc_teacher_id = public.my_teacher_id())
  WITH CHECK (public.is_performance_coach() AND pc_teacher_id = public.my_teacher_id());

-- program_types
CREATE POLICY "Admins can do everything on program_types" ON public.program_types FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Any logged-in user can read program_types" ON public.program_types FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Authenticated users can read program_types" ON public.program_types FOR SELECT USING (auth.uid() IS NOT NULL);

-- course_types
CREATE POLICY "Admins can manage course_types" ON public.course_types FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Any logged-in user can read course_types" ON public.course_types FOR SELECT USING (auth.uid() IS NOT NULL);

-- subject_categories
CREATE POLICY "Admins can do everything on subject_categories" ON public.subject_categories FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all subject_categories" ON public.subject_categories FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role));
CREATE POLICY "Performance coaches can manage subject_categories" ON public.subject_categories FOR ALL USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());
CREATE POLICY "Performance coaches can insert subject_categories" ON public.subject_categories FOR INSERT WITH CHECK (public.is_performance_coach());
CREATE POLICY "Any logged-in user can read subject_categories" ON public.subject_categories FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Authenticated users can read subject_categories" ON public.subject_categories FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Performance coaches can update subject_categories" ON public.subject_categories FOR UPDATE USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());

-- curricula
CREATE POLICY "Admins can do everything on curricula" ON public.curricula FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all curricula" ON public.curricula FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role));
CREATE POLICY "Authenticated users can insert curricula" ON public.curricula FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Performance coaches can insert curricula" ON public.curricula FOR INSERT WITH CHECK (public.is_performance_coach());
CREATE POLICY "Any logged-in user can read curricula" ON public.curricula FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Authenticated users can read curricula" ON public.curricula FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Performance coaches can update curricula" ON public.curricula FOR UPDATE USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());

-- curriculum_groups
CREATE POLICY "Admins can do everything on curriculum_groups" ON public.curriculum_groups FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Performance coaches can manage curriculum_groups" ON public.curriculum_groups FOR ALL USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());
CREATE POLICY "Any logged-in user can read curriculum_groups" ON public.curriculum_groups FOR SELECT USING (auth.uid() IS NOT NULL);

-- subjects
CREATE POLICY "Admins can do everything on subjects" ON public.subjects FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all subjects" ON public.subjects FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role));
CREATE POLICY "Performance coaches can manage subjects" ON public.subjects FOR ALL USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());
CREATE POLICY "Authenticated users can insert subjects" ON public.subjects FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "Performance coaches can insert subjects" ON public.subjects FOR INSERT WITH CHECK (public.is_performance_coach());
CREATE POLICY "Any logged-in user can read subjects" ON public.subjects FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Authenticated users can read subjects" ON public.subjects FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Performance coaches can update subjects" ON public.subjects FOR UPDATE USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());

-- session_logs
CREATE POLICY "Admins can do everything on session_logs" ON public.session_logs FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins can manage all session_logs" ON public.session_logs FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM public.users WHERE users.id = auth.uid() AND users.role = 'admin'::public.user_role));
CREATE POLICY "Teachers can insert their own session logs" ON public.session_logs FOR INSERT WITH CHECK (teacher_id = public.my_teacher_id());
CREATE POLICY "Teachers can insert their own session_logs" ON public.session_logs FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.teachers WHERE teachers.id = session_logs.teacher_id AND teachers.user_id = auth.uid()));
CREATE POLICY "PCs can read sessions for assigned students" ON public.session_logs FOR SELECT
  USING (public.is_performance_coach() AND student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL));
CREATE POLICY "Performance coaches can read all session_logs" ON public.session_logs FOR SELECT USING (public.is_performance_coach());
CREATE POLICY "Teachers can read their own session logs" ON public.session_logs FOR SELECT USING (teacher_id = public.my_teacher_id());
CREATE POLICY "Teachers can read their own session_logs" ON public.session_logs FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.teachers WHERE teachers.id = session_logs.teacher_id AND teachers.user_id = auth.uid()));
CREATE POLICY "Performance coaches can update session_logs" ON public.session_logs FOR UPDATE USING (public.is_performance_coach()) WITH CHECK (public.is_performance_coach());

-- student_packages
CREATE POLICY "admin_all_student_packages" ON public.student_packages FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "pc_manage_assigned_packages" ON public.student_packages FOR ALL
  USING (public.is_performance_coach() AND student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL))
  WITH CHECK (public.is_performance_coach() AND student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL));

-- package_topups
CREATE POLICY "admin_all_topups" ON public.package_topups FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "pc_insert_own_topups" ON public.package_topups FOR INSERT
  WITH CHECK (public.is_performance_coach() AND student_package_id IN (
    SELECT sp.id FROM public.student_packages sp WHERE sp.student_id IN (
      SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL)));
CREATE POLICY "pc_select_own_topups" ON public.package_topups FOR SELECT
  USING (public.is_performance_coach() AND student_package_id IN (
    SELECT sp.id FROM public.student_packages sp WHERE sp.student_id IN (
      SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL)));

-- invoices
CREATE POLICY "admin_all_invoices" ON public.invoices FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "pc_manage_assigned_invoices" ON public.invoices FOR ALL
  USING (public.is_performance_coach() AND student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL))
  WITH CHECK (public.is_performance_coach() AND student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL));

-- invoice_line_items
CREATE POLICY "admin_all_line_items" ON public.invoice_line_items FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "pc_manage_line_items" ON public.invoice_line_items FOR ALL
  USING (public.is_performance_coach() AND invoice_id IN (SELECT i.id FROM public.invoices i WHERE i.student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL)))
  WITH CHECK (public.is_performance_coach() AND invoice_id IN (SELECT i.id FROM public.invoices i WHERE i.student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL)));

-- invoice_packages
CREATE POLICY "admin_all_invoice_packages" ON public.invoice_packages FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "pc_manage_invoice_packages" ON public.invoice_packages FOR ALL
  USING (public.is_performance_coach() AND invoice_id IN (SELECT i.id FROM public.invoices i WHERE i.student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL)))
  WITH CHECK (public.is_performance_coach() AND invoice_id IN (SELECT i.id FROM public.invoices i WHERE i.student_id IN (SELECT pc_student_assignments.student_id FROM public.pc_student_assignments WHERE pc_student_assignments.pc_teacher_id = public.my_teacher_id() AND pc_student_assignments.unassigned_at IS NULL)));

-- monthly_reports
CREATE POLICY "admins manage monthly_reports" ON public.monthly_reports FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "teachers read locked monthly_reports" ON public.monthly_reports FOR SELECT USING (status = 'locked'::text);

-- monthly_report_teacher_stats
CREATE POLICY "admins manage monthly_report_teacher_stats" ON public.monthly_report_teacher_stats FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "teachers read own monthly_report_teacher_stats" ON public.monthly_report_teacher_stats FOR SELECT
  USING (teacher_id = public.my_teacher_id() AND EXISTS (SELECT 1 FROM public.monthly_reports mr WHERE mr.id = monthly_report_teacher_stats.report_id AND mr.status = 'locked'::text));

-- monthly_report_student_stats
CREATE POLICY "admins manage monthly_report_student_stats" ON public.monthly_report_student_stats FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- monthly_report_teacher_subject_stats
CREATE POLICY "admins manage monthly_report_teacher_subject_stats" ON public.monthly_report_teacher_subject_stats FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "teachers read own monthly_report_teacher_subject_stats" ON public.monthly_report_teacher_subject_stats FOR SELECT
  USING (teacher_id = public.my_teacher_id() AND EXISTS (SELECT 1 FROM public.monthly_reports mr WHERE mr.id = monthly_report_teacher_subject_stats.report_id AND mr.status = 'locked'::text));

-- monthly_report_student_subject_stats
CREATE POLICY "admins manage monthly_report_student_subject_stats" ON public.monthly_report_student_subject_stats FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- monthly_report_subject_stats
CREATE POLICY "admins manage monthly_report_subject_stats" ON public.monthly_report_subject_stats FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "teachers read locked monthly_report_subject_stats" ON public.monthly_report_subject_stats FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.monthly_reports mr WHERE mr.id = monthly_report_subject_stats.report_id AND mr.status = 'locked'::text));

-- zoom_invoices
CREATE POLICY "Admins can manage zoom invoices" ON public.zoom_invoices FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Teachers can upload their own zoom invoices" ON public.zoom_invoices FOR INSERT WITH CHECK (teacher_id = public.my_teacher_id());
CREATE POLICY "Teachers can view their own zoom invoices" ON public.zoom_invoices FOR SELECT USING (teacher_id = public.my_teacher_id() OR public.is_admin());
CREATE POLICY "Teachers can replace their own pending zoom invoices" ON public.zoom_invoices FOR UPDATE
  USING (teacher_id = public.my_teacher_id() AND status = 'pending'::text)
  WITH CHECK (teacher_id = public.my_teacher_id() AND status = 'pending'::text);

-- =========================================================================
-- 12. Grants
--
-- RLS policies only take effect on top of these base grants — a role with
-- no grant is blocked before RLS is ever evaluated. Reproduced exactly as
-- found live, including the zoom_invoices gap flagged at the top of this
-- file (authenticated has no SELECT/INSERT/UPDATE/DELETE grant there at
-- all, despite policies that assume it does).
-- =========================================================================

GRANT SELECT ON TABLE public.users TO anon;

GRANT SELECT, INSERT, UPDATE ON TABLE public.users TO authenticated; -- no DELETE, by design
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.teachers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.teacher_subjects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.admins TO authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.students TO authenticated; -- no DELETE, by design
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pc_student_assignments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.program_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.course_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subject_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.curricula TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.curriculum_groups TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subjects TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.session_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.student_packages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.package_topups TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.invoices TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.invoice_line_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.invoice_packages TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_reports TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_report_teacher_stats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_report_student_stats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_report_teacher_subject_stats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_report_student_subject_stats TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.monthly_report_subject_stats TO authenticated;
-- NOTE: public.zoom_invoices intentionally has NO grant to authenticated
-- here, matching the live database at the time this file was written (see
-- file header) — that gap is fixed by the very next migration,
-- 20260701000001_fix_zoom_invoices_authenticated_grant.sql.

-- The original 6-table design also granted service_role explicit full
-- access (redundant with service_role's RLS-bypass, but reproduced exactly
-- since it's genuinely present live). Later-added tables rely solely on
-- service_role's implicit bypass instead.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.admins TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.program_types TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.session_logs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.teacher_subjects TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.teachers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.users TO service_role;

-- =========================================================================
-- 13. Storage buckets & policies
-- =========================================================================

INSERT INTO storage.buckets (id, name, public) VALUES
  ('avatars', 'avatars', true),
  ('session-summaries', 'session-summaries', true),
  ('session-invoices', 'session-invoices', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Avatars are publicly readable" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
CREATE POLICY "Users can upload their own avatar" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Users can update their own avatar" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Authenticated users can read summaries" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'session-summaries');
CREATE POLICY "Authenticated users can upload summaries" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'session-summaries');

CREATE POLICY "Authenticated users can read invoices" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'session-invoices');
CREATE POLICY "Authenticated users can upload invoices" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'session-invoices');

-- Note (from the security advisor): all three buckets are public and their
-- SELECT policies allow listing all objects in the bucket, not just fetching
-- by known URL. Low risk for this use case, reproduced as-is; tighten later
-- if file enumeration becomes a concern.

-- =========================================================================
-- 14. Edge Functions (not SQL — deployed separately, listed here for
--     completeness since this migration aims to document "everything")
-- =========================================================================
-- create-teacher-with-user  (JWT required) — supabase/functions/create-teacher-with-user/index.ts
-- notify-no-show            (no JWT)       — supabase/functions/notify-no-show/index.ts
-- notify-flag               (JWT required) — supabase/functions/notify-flag/index.ts
-- Deploy each with: supabase functions deploy <slug>
-- Each requires SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM secrets
-- (create-teacher-with-user also needs SUPABASE_SERVICE_ROLE_KEY, provided
-- automatically by the Supabase platform).
